<a href="https://colab.research.google.com/github/aarya078/July26/blob/main/Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [9]:
import pandas as pd
name = ["a","b"]
df = pd.Series(name)
print(df)

0    a
1    b
dtype: object

In [10]:
#importing csv
df = pd.read_csv("Zomato-data-.csv")
#performing operations

In [11]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [13]:
df.sample() # provides any random data which can be provided in braces
# each time the data being chosen gets changed

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
119,K27 - The Pub,No,No,3.1/5,30,900,Dining

In [15]:
df.shape # used too calculate total rows and columns

(148, 7)

In [16]:
df.dtypes # provides datatype of each column

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [18]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [19]:
df.info() #analyzes complete set of data provided

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [20]:
df.describe() #

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [51]:
df["name"] #describing a particular column
df[["rate","name"]] # for multiple columns use double[]
#additional usage of features
#checking specific comparison results
df[df['rate']  > '3.1']
#comparison including both rate and votes was showcasing error
df[(df['listed_in(type)'] == 'Dining') & (df['book_table']=='Yes')] #checking multiple conditons
#dataTypes are crucial during comparison

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
61,Goa 0 Km,Yes,Yes,3.6/5,163,800,Dining
63,Jeet Restaurant,No,Yes,4.0/5,808,850,Dining

In [53]:
df.sort_values("votes",ascending= False ) # for descending order
df.sort_values("votes") #for ascending order

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
110,Hari Super Sandwich,No,No,3.2/5,0,200,Dining
107,Coffee Shopee,No,No,3.4/5,0,250,Dining
117,Kulfi & More,No,No,3.4/5,0,150,Dining
118,Kannadigas Karavali,No,No,3.4/5,0,250,Dining
116,Wood Stove,No,No,3.4/5,0,150,Dining
...,...,...,...,...,...,...,...
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
44,Onesta,Yes,Yes,4.6/5,2556,600,other
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other

In [58]:
df.rename(columns={"name" : "customer"}) #renaming any partcular column
df.rename(columns={"name" : "customer"} ,inplace = True) #renaming any partcular column and fixing it
#but not displaying anything for line 2

In [60]:
df.isnull().sum()
# to check if any null or zero value exists . sum() calculates the total number of times it occcured
df['votes'].isnull().sum()
#checking for a specific column

np.int64(0)

In [64]:
data = {"Roll_no." : [34,35,36,37],
        "Name ":["Anuj","Bablu","Chintu","Doxy"],
         "CGPA ":[9.0,7.8,8.9,8.8],
         "Placed ":["Yes","Yes", "Yes","Yes"]}
dff= pd.DataFrame(data)
print(dff)

   Roll_no.   Name   CGPA  Placed
0        34    Anuj    9.0     Yes
1        35   Bablu    7.8     Yes
2        36  Chintu    8.9     Yes
3        37    Doxy    8.8     Yes

In [66]:
dff.head() #showcasing the data frames

   Roll_no.   Name   CGPA  Placed
0        34    Anuj    9.0     Yes
1        35   Bablu    7.8     Yes
2        36  Chintu    8.9     Yes
3        37    Doxy    8.8     Yes

In [67]:
dff.head(3) #displays only 3 rows

   Roll_no.   Name   CGPA  Placed
0        34    Anuj    9.0     Yes
1        35   Bablu    7.8     Yes
2        36  Chintu    8.9     Yes

In [69]:
dff.describe() # displays statistical analyzed data of provied numeric values

        Roll_no.     CGPA
count   4.000000  4.000000
mean   35.500000  8.625000
std     1.290994  0.556028
min    34.000000  7.800000
25%    34.750000  8.550000
50%    35.500000  8.850000
75%    36.250000  8.925000
max    37.000000  9.000000

In [74]:
dff.sample() #randomly displays a row
dff.sample(2) # randomly selects and displays rows as mentioned in index

   Roll_no.   Name   CGPA  Placed
1        35   Bablu    7.8     Yes
2        36  Chintu    8.9     Yes

In [73]:
dff.dtypes # highlights the dataType of each column

Roll_no.      int64
Name         object
CGPA        float64
Placed       object
dtype: object

In [75]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Roll_no.  4 non-null      int64
 1   Name      4 non-null      object
 2   CGPA      4 non-null      float64
 3   Placed    4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes